name: Issue 2
description: This is issue 2
title: "[Issue 2]:"
labels: ["Issue2"]
body:
  type: input
  id: input_1
  attributes:
    label: Input 1
    description: This is input 1
  validations:
    required: true
